### ISSUE TITLE
Using `pnpm start` doesn't work on v4

### ISSUE THREAD

**Issue by thecmdrunner** [thecmdrunner/remotion-gtts-template#8]
## Steps to reproduce
- `pnpm i`
- `pnpm start`

## What I tried
Using `npm` instead of `pnpm` works fine though.
- `npm i`
- `npm start`

```shell
fedora :: remotion-gtts-template-v4 » pnpm start

> remotion-gtts-template@1.0.0 start /home/thegamerhat/Git-Projects/remotion-gtts-template-v4
> ts-node src/studio.ts


/home/thegamerhat/Git-Projects/remotion-gtts-template-v4/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/typescript.js:43495
        ts.Debug.assert(typeof typeReferenceDirectiveName === "string", "Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.");
                 ^
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Object.resolveTypeReferenceDirective (/home/thegamerhat/Git-Projects/remotion-gtts-template-v4/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/typescript.js:43495:18)
    at /home/thegamerhat/Git-Projects/remotion-gtts-template-v4/node_modules/.pnpm/ts-node@10.0.0_@types+node@18.15.11_typescript@4.9.4/node_modules/ts-node/src/index.ts:737:16
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (/home/thegamerhat/Git-Projects/remotion-gtts-template-v4/node_modules/.pnpm/ts-node@10.0.0_@types+node@18.15.11_typescript@4.9.4/node_modules/ts-node/src/index.ts:734:33)
    at actualResolveTypeReferenceDirectiveNamesWorker (/home/thegamerhat/Git-Projects/remotion-gtts-template-v4/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/typescript.js:119377:163)
    at resolveTypeReferenceDirectiveNamesWorker (/home/thegamerhat/Git-Projects/remotion-gtts-template-v4/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/typescript.js:119677:26)
    at processTypeReferenceDirectives (/home/thegamerhat/Git-Projects/remotion-gtts-template-v4/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/typescript.js:121180:31)
    at findSourceFileWorker (/home/thegamerhat/Git-Projects/remotion-gtts-template-v4/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/typescript.js:121065:21)
    at findSourceFile (/home/thegamerhat/Git-Projects/remotion-gtts-template-v4/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/typescript.js:120917:26)
    at processImportedModules (/home/thegamerhat/Git-Projects/remotion-gtts-template-v4/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/typescript.js:121326:25)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by JonnyBurger** [comment]
Thanks for testing and reporting this @thecmdrunner!!

**Comment by thecmdrunner** [comment]
@JonnyBurger Thank you for fixing so quick! Waiting for the v4 keynote 😁
